# Generated by Django 4.1.7 on 2023-03-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('children', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_children', to='menu.category')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_parent', to='menu.category')),
            ],
        ),
    ]
