# Generated by Django 4.1.7 on 2023-03-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_parent', to='menu.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='link_children', to='menu.category'),
        ),
    ]
