# Generated by Django 4.1.7 on 2023-03-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='visible',
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
